gapic_generator_version: 2.64.1
googleapis_commitish: 8c06c1e04ae562f49f411357577c700e9142f33c
libraries_bom_version: 26.72.0
libraries:
  - api_shortname: pubsublite
    name_pretty: Cloud Pub/Sub Lite
    product_documentation: https://cloud.google.com/pubsub/lite/docs
    api_description: is designed to provide reliable, many-to-many, asynchronous messaging between applications. Publisher\napplications can send messages to a topic and other applications can\nsubscribe to that topic to receive the messages. By decoupling senders and\nreceivers, Google Cloud Pub/Sub allows developers to communicate between\nindependently written applications.\n\nCompared to Google Pub/Sub, Pub/Sub Lite provides partitioned zonal data\nstorage with predefined capacity. Both products present a similar API, but\nPub/Sub Lite has more usage caveats.\n\nSee the [Google Pub/Sub Lite docs](https://cloud.google.com/pubsub/quickstart-console#before-you-begin) for more details on how to activate\nPub/Sub Lite for your project, as well as guidance on how to choose between\nCloud Pub/Sub and Pub/Sub Lite.
    client_documentation: https://cloud.google.com/java/docs/reference/google-cloud-pubsublite/latest/history
    release_level: stable
    transport: grpc
    requires_billing: true
    language: java
    min_java_version: 8
    repo: googleapis/java-pubsublite
    repo_short: java-pubsublite
    distribution_name: com.google.cloud:google-cloud-pubsublite
    codeowner_team: '@googleapis/api-pubsublite'
    library_type: GAPIC_COMBO
    api_id: pubsublite.googleapis.com
    recommended_package: com.google.cloud.pubsublite.cloudpubsub
    GAPICs:
      - proto_path: google/cloud/pubsublite/v1
